@extends('layouts.staff')
@section('title', 'Operations dashboard')
@section('styles')
<style>
    .dash-hero{position:relative;overflow:hidden;padding:2rem;color:#fff;background:linear-gradient(125deg,#082f20,#115b3b);border-radius:22px}.dash-hero h1{color:#fff!important;font-weight:800;letter-spacing:-.045em}.dash-hero p{color:rgba(255,255,255,.68)}.dash-chip{display:inline-flex;gap:.4rem;padding:.45rem .65rem;background:rgba(255,255,255,.1);border-radius:999px;font-size:.7rem;font-weight:800}.metric-card{height:100%;padding:1.25rem}.metric-icon{display:grid;width:42px;height:42px;place-items:center;color:#176b45;background:#e8f4ed;border-radius:11px;font-size:1.2rem}.metric-value{margin-top:1rem;font-size:1.9rem;font-weight:800;letter-spacing:-.04em}.metric-label{color:#76837b;font-size:.76rem}.panel-head{padding:1.2rem 1.3rem;border-bottom:1px solid var(--staff-line)}.panel-head h2{margin:0;font-size:1rem;font-weight:800}.top-phone{display:flex;align-items:center;gap:.85rem;padding:.85rem 1.2rem;border-bottom:1px solid #edf1ee}.top-phone:last-child{border-bottom:0}.top-phone__image{display:grid;width:54px;height:54px;flex:0 0 54px;place-items:center;overflow:hidden;background:#f0f4f1;border-radius:10px}.top-phone__image img{width:100%;height:100%;object-fit:contain}.top-phone strong{display:block;font-size:.8rem}.top-phone small{color:#7b8780}.view-pill{margin-left:auto;padding:.35rem .55rem;color:#176b45;background:#eaf4ed;border-radius:999px;font-size:.68rem;font-weight:800}.brand-row{padding:.7rem 1.2rem}.brand-bar{height:7px;margin-top:.4rem;overflow:hidden;background:#edf2ee;border-radius:99px}.brand-bar span{display:block;height:100%;background:linear-gradient(90deg,#176b45,#54a573);border-radius:99px}.invite-box{padding:1.35rem}.table>:not(caption)>*>*{padding:.9rem 1.2rem}.empty-state{padding:2rem;color:#7b8780;text-align:center}@media(max-width:767px){.dash-hero{padding:1.4rem}.metric-value{font-size:1.55rem}}
</style>
@endsection
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->has('invite'))<div class="alert alert-danger">{{ $errors->first('invite') }}</div>@endif
<section class="dash-hero mb-4"><span class="dash-chip"><i class="ri-pulse-line"></i> LIVE OPERATIONS OVERVIEW</span><h1 class="mt-3 mb-2">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 18 ? 'afternoon' : 'evening') }}, {{ Str::before(auth()->user()->name, ' ') }}.</h1><p class="mb-0">See what customers are viewing and where catalogue attention is needed.</p></section>
<div class="row g-3 mb-4">
@foreach([
 ['ri-smartphone-line','Active variants',$counts['variants']],['ri-eye-line','All product views',$counts['views']],['ri-line-chart-line','Views in 7 days',$counts['views_7d']],['ri-archive-line','Missing stock data',$counts['missing_stock']],['ri-image-line','Missing images',$counts['missing_images']],['ri-price-tag-3-line','Price on request',$counts['quote_required']]
] as [$icon,$label,$value])<div class="col-6 col-lg-2"><div class="staff-card metric-card"><span class="metric-icon"><i class="{{ $icon }}"></i></span><div class="metric-value">{{ number_format($value) }}</div><div class="metric-label">{{ $label }}</div></div></div>@endforeach
</div>
<div class="row g-4 mb-4"><div class="col-xl-7"><section class="staff-card h-100"><div class="panel-head d-flex justify-content-between"><h2>Most viewed phones</h2><small class="text-muted">Since tracking began</small></div>@forelse($topViewed as $phone)<div class="top-phone"><div class="top-phone__image">@if(filled($phone->image_path) && is_file(public_path($phone->image_path)))<img src="{{ asset($phone->image_path) }}" alt="">@else<i class="ri-image-line text-muted"></i>@endif</div><div><strong>{{ $phone->name }}</strong><small>{{ $phone->product->brand->name }} · {{ $phone->price ? 'KES '.number_format($phone->price) : 'Price on request' }}</small></div><span class="view-pill">{{ number_format($phone->view_metrics_sum_view_count ?? 0) }} views</span></div>@empty<div class="empty-state">Product views will appear here as customers open phone details.</div>@endforelse</section></div><div class="col-xl-5"><section class="staff-card h-100"><div class="panel-head"><h2>Catalogue by brand</h2></div>@php($maxBrand = max(1, (int) $brandInsights->max('variant_count')))@foreach($brandInsights as $brand)<div class="brand-row"><div class="d-flex justify-content-between small"><strong>{{ $brand->name }}</strong><span class="text-muted">{{ $brand->variant_count }}</span></div><div class="brand-bar"><span style="width:{{ ($brand->variant_count / $maxBrand) * 100 }}%"></span></div></div>@endforeach</section></div></div>
<div class="row g-4"><div class="col-xl-7"><section class="staff-card overflow-hidden"><div class="panel-head"><h2>Recent stock updates</h2></div>@if($recentStock->isEmpty())<div class="empty-state"><i class="ri-archive-line fs-3 d-block mb-2"></i>No stock source connected yet. Products remain marked “Confirm availability.”</div>@else<div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Phone</th><th>Location</th><th>Status</th><th>Observed</th></tr></thead><tbody>@foreach($recentStock as $stock)<tr><td>{{ $stock->variant->name }}</td><td>{{ $stock->location->name }}</td><td>{{ str($stock->status)->replace('_',' ')->title() }}</td><td>{{ $stock->observed_at?->diffForHumans() }}</td></tr>@endforeach</tbody></table></div>@endif</section></div>
<div class="col-xl-5">@if(auth()->user()->role === 'admin')<section class="staff-card invite-box"><div class="d-flex justify-content-between align-items-start gap-3"><div><span class="text-success small fw-bold">TEAM ACCESS</span><h2 class="h5 fw-bold mt-2">Invite another staff member</h2></div><a href="{{ route('staff.team.index') }}" class="btn btn-sm btn-outline-success">Manage team</a></div><p class="text-muted small">They will receive a secure link to create their own password.</p>@if($errors->any())<div class="alert alert-danger py-2 small">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('staff.invitations.store') }}">@csrf<div class="row g-2"><div class="col-sm-6"><input name="name" value="{{ old('name') }}" class="form-control" placeholder="Full name" required></div><div class="col-sm-6"><select name="role" class="form-select"><option value="staff" @selected(old('role') === 'staff')>Staff</option><option value="admin" @selected(old('role') === 'admin')>Administrator</option></select></div><div class="col-12"><input type="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="name@example.com" required></div><div class="col-12"><input name="subject" value="{{ old('subject', 'You are invited to the Phone Express staff portal') }}" class="form-control" placeholder="Email subject" maxlength="150"></div><div class="col-12"><textarea name="custom_message" class="form-control" rows="3" maxlength="1200" placeholder="Add a personal note (optional)">{{ old('custom_message') }}</textarea></div><div class="col-12"><button class="btn btn-staff w-100 py-3"><i class="ri-mail-send-line me-1"></i> Send secure invitation</button></div></div></form></section>@endif
<section class="staff-card mt-4"><div class="panel-head"><h2>Recent invitations</h2></div>@forelse($recentInvitations as $invite)<div class="top-phone"><span class="metric-icon"><i class="ri-user-add-line"></i></span><div><strong>{{ $invite->name ?: $invite->email }}</strong><small>{{ $invite->accepted_at ? 'Accepted' : ($invite->sent_at ? 'Sent' : 'Pending') }} · {{ ucfirst($invite->role) }}</small></div></div>@empty<div class="empty-state">No invitations yet.</div>@endforelse</section></div></div>
@endsection
