@extends('layouts.staff')
@section('title', 'Team access')
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="d-flex justify-content-between align-items-end mb-4"><div><span class="text-success small fw-bold">ADMINISTRATION</span><h1 class="h2 fw-bold mb-0">Team access</h1><p class="text-muted mb-0">Revoke or restore access without deleting staff history.</p></div></div>
<section class="staff-card overflow-hidden mb-4"><div class="p-4 border-bottom"><h2 class="h5 mb-0">Staff accounts</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>@foreach($members as $member)<tr><td>{{ $member->name }}</td><td>{{ $member->email }}</td><td>{{ ucfirst($member->role) }}</td><td><span class="badge {{ $member->is_active ? 'bg-success' : 'bg-secondary' }}">{{ $member->is_active ? 'Active' : 'Revoked' }}</span></td><td class="text-end">@if(!auth()->user()->is($member))<form method="POST" action="{{ $member->is_active ? route('staff.team.revoke',$member) : route('staff.team.restore',$member) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $member->is_active ? 'btn-outline-danger' : 'btn-outline-success' }}">{{ $member->is_active ? 'Revoke access' : 'Restore access' }}</button></form>@else<span class="text-muted small">Current account</span>@endif</td></tr>@endforeach</tbody></table></div></section>
<div class="row g-4"><div class="col-xl-7"><section class="staff-card overflow-hidden"><div class="p-4 border-bottom"><h2 class="h5 mb-0">Recent invitations</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Recipient</th><th>Status</th><th>Expires</th><th></th></tr></thead><tbody>@forelse($invitations as $invite)<tr><td>{{ $invite->name }}<small class="d-block text-muted">{{ $invite->email }} · {{ ucfirst($invite->role) }}</small></td><td>{{ $invite->accepted_at ? 'Accepted' : ($invite->revoked_at ? 'Revoked' : ($invite->expires_at->isPast() ? 'Expired' : 'Pending')) }}</td><td>{{ $invite->expires_at->diffForHumans() }}</td><td class="text-end">@if(!$invite->accepted_at && !$invite->revoked_at)<form method="POST" action="{{ route('staff.invitations.revoke',$invite) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-danger">Cancel</button></form>@endif</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">No invitations yet.</td></tr>@endforelse</tbody></table></div></section></div><div class="col-xl-5"><section class="staff-card p-4"><span class="text-success small fw-bold">NEW INVITATION</span><h2 class="h4 fw-bold mt-2">Invite a team member</h2><p class="text-muted small">Customize the email they receive. Their secure setup link expires automatically.</p><form method="POST" action="{{ route('staff.invitations.store') }}">@csrf<div class="row g-3"><div class="col-sm-7"><label class="form-label fw-semibold">Full name</label><input name="name" value="{{ old('name') }}" class="form-control" required></div><div class="col-sm-5"><label class="form-label fw-semibold">Access</label><select name="role" class="form-select"><option value="staff" @selected(old('role')==='staff')>Staff</option><option value="admin" @selected(old('role')==='admin')>Administrator</option></select></div><div class="col-12"><label class="form-label fw-semibold">Email</label><input type="email" name="email" value="{{ old('email') }}" class="form-control" required></div><div class="col-12"><label class="form-label fw-semibold">Email subject <span class="text-muted fw-normal">(optional)</span></label><input name="subject" value="{{ old('subject') }}" class="form-control" placeholder="You’re invited to Phone Express"></div><div class="col-12"><label class="form-label fw-semibold">Personal message <span class="text-muted fw-normal">(optional)</span></label><textarea name="custom_message" rows="4" class="form-control" placeholder="Add a short welcome note...">{{ old('custom_message') }}</textarea></div><div class="col-12"><button class="btn btn-staff w-100 py-3"><i class="ri-mail-send-line me-1"></i> Send secure invitation</button></div></div></form></section></div></div>
@endsection
